# Generated by Django 5.0.4 on 2024-04-06 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 14, 30, 22, 707339, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 14, 30, 22, 706740, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
